baseURL = 'https://kanade2001.netlify.app'
languageCode = 'en-us'
title = 'Kanadeのほーむぺーじ'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
    news = [
        "2024/03/25: ホームページ開設"
    ]
    github = "https://github.com/kanade2001"
    twitter = "https://twitter.com/kanade2001_cpp"